/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package main;

/*import controller.ProjectController;
import controller.TaskController;
import java.util.Date;
import model.Project;
import model.Task;*/

public class App {
    public static void main(String[] args){
        
       /* TaskController taskController = new TaskController();
        Task task = new Task();
        task.setIdProject(6);
        task.setName("Task teste");
        task.setDescription("Description Teste");
        task.setNotes("Notes teste");
        task.setDeadLine(new Date());
        task.setCreatedAt(new Date());
        task.setUptatedAt(new Date());
        taskController.save(task);*/
        
       
    }
}
